# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_and_reg', '0003_comment_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
