# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 01:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_and_reg', '0004_auto_20170131_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
