# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_and_reg', '0005_user_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
